/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as RefRouteImport } from './routes/ref'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShopIndexRouteImport } from './routes/shop/index'
import { Route as ProfileIndexRouteImport } from './routes/profile/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as ShopPayoutRouteImport } from './routes/shop/payout'
import { Route as ShopOrderStatusRouteImport } from './routes/shop/order-status'
import { Route as ShopMintRouteImport } from './routes/shop/mint'
import { Route as ShopCustomizationRouteImport } from './routes/shop/customization'
import { Route as ProfileSettingsRouteImport } from './routes/profile/settings'
import { Route as ProfileUsernameRouteImport } from './routes/profile/$username'
import { Route as DashboardVouchRouteImport } from './routes/dashboard/vouch'
import { Route as DashboardScoreRouteImport } from './routes/dashboard/score'
import { Route as DashboardReferralStatsRouteImport } from './routes/dashboard/referral-stats'
import { Route as DashboardNftsRouteImport } from './routes/dashboard/nfts'
import { Route as DashboardMyDashboardRouteImport } from './routes/dashboard/my-dashboard'
import { Route as DashboardGuudFriendsRouteImport } from './routes/dashboard/guud-friends'
import { Route as DashboardGuudCardRouteImport } from './routes/dashboard/guud-card'
import { Route as DashboardBribeRouteImport } from './routes/dashboard/bribe'
import { Route as DashboardAssetsRouteImport } from './routes/dashboard/assets'
import { Route as DashboardArenaYappingRouteImport } from './routes/dashboard/arena-yapping'
import { Route as AuthErrorRouteImport } from './routes/auth/error'
import { Route as AgentProfileAgentIdRouteImport } from './routes/agent-profile.$agentId'
import { Route as ProfileSettingsIndexRouteImport } from './routes/profile/settings/index'
import { Route as ProfileSettingsStyleRouteImport } from './routes/profile/settings/style'
import { Route as ProfileSettingsSocialRouteImport } from './routes/profile/settings/social'
import { Route as ProfileSettingsNftsRouteImport } from './routes/profile/settings/nfts'
import { Route as ProfileSettingsBribeRouteImport } from './routes/profile/settings/bribe'
import { Route as ProfileSettingsBasicRouteImport } from './routes/profile/settings/basic'
import { Route as ProfileSettingsArenaRouteImport } from './routes/profile/settings/arena'
import { Route as ProfileSettingsAppearanceRouteImport } from './routes/profile/settings/appearance'
import { Route as AuthCallbackTwitterRouteImport } from './routes/auth/callback/twitter'

const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const RefRoute = RefRouteImport.update({
  id: '/ref',
  path: '/ref',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShopRoute,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProfileRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const ShopPayoutRoute = ShopPayoutRouteImport.update({
  id: '/payout',
  path: '/payout',
  getParentRoute: () => ShopRoute,
} as any)
const ShopOrderStatusRoute = ShopOrderStatusRouteImport.update({
  id: '/order-status',
  path: '/order-status',
  getParentRoute: () => ShopRoute,
} as any)
const ShopMintRoute = ShopMintRouteImport.update({
  id: '/mint',
  path: '/mint',
  getParentRoute: () => ShopRoute,
} as any)
const ShopCustomizationRoute = ShopCustomizationRouteImport.update({
  id: '/customization',
  path: '/customization',
  getParentRoute: () => ShopRoute,
} as any)
const ProfileSettingsRoute = ProfileSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ProfileRoute,
} as any)
const ProfileUsernameRoute = ProfileUsernameRouteImport.update({
  id: '/$username',
  path: '/$username',
  getParentRoute: () => ProfileRoute,
} as any)
const DashboardVouchRoute = DashboardVouchRouteImport.update({
  id: '/vouch',
  path: '/vouch',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardScoreRoute = DashboardScoreRouteImport.update({
  id: '/score',
  path: '/score',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardReferralStatsRoute = DashboardReferralStatsRouteImport.update({
  id: '/referral-stats',
  path: '/referral-stats',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardNftsRoute = DashboardNftsRouteImport.update({
  id: '/nfts',
  path: '/nfts',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMyDashboardRoute = DashboardMyDashboardRouteImport.update({
  id: '/my-dashboard',
  path: '/my-dashboard',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardGuudFriendsRoute = DashboardGuudFriendsRouteImport.update({
  id: '/guud-friends',
  path: '/guud-friends',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardGuudCardRoute = DashboardGuudCardRouteImport.update({
  id: '/guud-card',
  path: '/guud-card',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBribeRoute = DashboardBribeRouteImport.update({
  id: '/bribe',
  path: '/bribe',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAssetsRoute = DashboardAssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardArenaYappingRoute = DashboardArenaYappingRouteImport.update({
  id: '/arena-yapping',
  path: '/arena-yapping',
  getParentRoute: () => DashboardRoute,
} as any)
const AuthErrorRoute = AuthErrorRouteImport.update({
  id: '/auth/error',
  path: '/auth/error',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentProfileAgentIdRoute = AgentProfileAgentIdRouteImport.update({
  id: '/agent-profile/$agentId',
  path: '/agent-profile/$agentId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileSettingsIndexRoute = ProfileSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProfileSettingsRoute,
} as any)
const ProfileSettingsStyleRoute = ProfileSettingsStyleRouteImport.update({
  id: '/style',
  path: '/style',
  getParentRoute: () => ProfileSettingsRoute,
} as any)
const ProfileSettingsSocialRoute = ProfileSettingsSocialRouteImport.update({
  id: '/social',
  path: '/social',
  getParentRoute: () => ProfileSettingsRoute,
} as any)
const ProfileSettingsNftsRoute = ProfileSettingsNftsRouteImport.update({
  id: '/nfts',
  path: '/nfts',
  getParentRoute: () => ProfileSettingsRoute,
} as any)
const ProfileSettingsBribeRoute = ProfileSettingsBribeRouteImport.update({
  id: '/bribe',
  path: '/bribe',
  getParentRoute: () => ProfileSettingsRoute,
} as any)
const ProfileSettingsBasicRoute = ProfileSettingsBasicRouteImport.update({
  id: '/basic',
  path: '/basic',
  getParentRoute: () => ProfileSettingsRoute,
} as any)
const ProfileSettingsArenaRoute = ProfileSettingsArenaRouteImport.update({
  id: '/arena',
  path: '/arena',
  getParentRoute: () => ProfileSettingsRoute,
} as any)
const ProfileSettingsAppearanceRoute =
  ProfileSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => ProfileSettingsRoute,
  } as any)
const AuthCallbackTwitterRoute = AuthCallbackTwitterRouteImport.update({
  id: '/auth/callback/twitter',
  path: '/auth/callback/twitter',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRouteWithChildren
  '/ref': typeof RefRoute
  '/register': typeof RegisterRoute
  '/shop': typeof ShopRouteWithChildren
  '/agent-profile/$agentId': typeof AgentProfileAgentIdRoute
  '/auth/error': typeof AuthErrorRoute
  '/dashboard/arena-yapping': typeof DashboardArenaYappingRoute
  '/dashboard/assets': typeof DashboardAssetsRoute
  '/dashboard/bribe': typeof DashboardBribeRoute
  '/dashboard/guud-card': typeof DashboardGuudCardRoute
  '/dashboard/guud-friends': typeof DashboardGuudFriendsRoute
  '/dashboard/my-dashboard': typeof DashboardMyDashboardRoute
  '/dashboard/nfts': typeof DashboardNftsRoute
  '/dashboard/referral-stats': typeof DashboardReferralStatsRoute
  '/dashboard/score': typeof DashboardScoreRoute
  '/dashboard/vouch': typeof DashboardVouchRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/profile/settings': typeof ProfileSettingsRouteWithChildren
  '/shop/customization': typeof ShopCustomizationRoute
  '/shop/mint': typeof ShopMintRoute
  '/shop/order-status': typeof ShopOrderStatusRoute
  '/shop/payout': typeof ShopPayoutRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/shop/': typeof ShopIndexRoute
  '/auth/callback/twitter': typeof AuthCallbackTwitterRoute
  '/profile/settings/appearance': typeof ProfileSettingsAppearanceRoute
  '/profile/settings/arena': typeof ProfileSettingsArenaRoute
  '/profile/settings/basic': typeof ProfileSettingsBasicRoute
  '/profile/settings/bribe': typeof ProfileSettingsBribeRoute
  '/profile/settings/nfts': typeof ProfileSettingsNftsRoute
  '/profile/settings/social': typeof ProfileSettingsSocialRoute
  '/profile/settings/style': typeof ProfileSettingsStyleRoute
  '/profile/settings/': typeof ProfileSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/ref': typeof RefRoute
  '/register': typeof RegisterRoute
  '/agent-profile/$agentId': typeof AgentProfileAgentIdRoute
  '/auth/error': typeof AuthErrorRoute
  '/dashboard/arena-yapping': typeof DashboardArenaYappingRoute
  '/dashboard/assets': typeof DashboardAssetsRoute
  '/dashboard/bribe': typeof DashboardBribeRoute
  '/dashboard/guud-card': typeof DashboardGuudCardRoute
  '/dashboard/guud-friends': typeof DashboardGuudFriendsRoute
  '/dashboard/my-dashboard': typeof DashboardMyDashboardRoute
  '/dashboard/nfts': typeof DashboardNftsRoute
  '/dashboard/referral-stats': typeof DashboardReferralStatsRoute
  '/dashboard/score': typeof DashboardScoreRoute
  '/dashboard/vouch': typeof DashboardVouchRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/shop/customization': typeof ShopCustomizationRoute
  '/shop/mint': typeof ShopMintRoute
  '/shop/order-status': typeof ShopOrderStatusRoute
  '/shop/payout': typeof ShopPayoutRoute
  '/dashboard': typeof DashboardIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/shop': typeof ShopIndexRoute
  '/auth/callback/twitter': typeof AuthCallbackTwitterRoute
  '/profile/settings/appearance': typeof ProfileSettingsAppearanceRoute
  '/profile/settings/arena': typeof ProfileSettingsArenaRoute
  '/profile/settings/basic': typeof ProfileSettingsBasicRoute
  '/profile/settings/bribe': typeof ProfileSettingsBribeRoute
  '/profile/settings/nfts': typeof ProfileSettingsNftsRoute
  '/profile/settings/social': typeof ProfileSettingsSocialRoute
  '/profile/settings/style': typeof ProfileSettingsStyleRoute
  '/profile/settings': typeof ProfileSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRouteWithChildren
  '/ref': typeof RefRoute
  '/register': typeof RegisterRoute
  '/shop': typeof ShopRouteWithChildren
  '/agent-profile/$agentId': typeof AgentProfileAgentIdRoute
  '/auth/error': typeof AuthErrorRoute
  '/dashboard/arena-yapping': typeof DashboardArenaYappingRoute
  '/dashboard/assets': typeof DashboardAssetsRoute
  '/dashboard/bribe': typeof DashboardBribeRoute
  '/dashboard/guud-card': typeof DashboardGuudCardRoute
  '/dashboard/guud-friends': typeof DashboardGuudFriendsRoute
  '/dashboard/my-dashboard': typeof DashboardMyDashboardRoute
  '/dashboard/nfts': typeof DashboardNftsRoute
  '/dashboard/referral-stats': typeof DashboardReferralStatsRoute
  '/dashboard/score': typeof DashboardScoreRoute
  '/dashboard/vouch': typeof DashboardVouchRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/profile/settings': typeof ProfileSettingsRouteWithChildren
  '/shop/customization': typeof ShopCustomizationRoute
  '/shop/mint': typeof ShopMintRoute
  '/shop/order-status': typeof ShopOrderStatusRoute
  '/shop/payout': typeof ShopPayoutRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/shop/': typeof ShopIndexRoute
  '/auth/callback/twitter': typeof AuthCallbackTwitterRoute
  '/profile/settings/appearance': typeof ProfileSettingsAppearanceRoute
  '/profile/settings/arena': typeof ProfileSettingsArenaRoute
  '/profile/settings/basic': typeof ProfileSettingsBasicRoute
  '/profile/settings/bribe': typeof ProfileSettingsBribeRoute
  '/profile/settings/nfts': typeof ProfileSettingsNftsRoute
  '/profile/settings/social': typeof ProfileSettingsSocialRoute
  '/profile/settings/style': typeof ProfileSettingsStyleRoute
  '/profile/settings/': typeof ProfileSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/leaderboard'
    | '/login'
    | '/profile'
    | '/ref'
    | '/register'
    | '/shop'
    | '/agent-profile/$agentId'
    | '/auth/error'
    | '/dashboard/arena-yapping'
    | '/dashboard/assets'
    | '/dashboard/bribe'
    | '/dashboard/guud-card'
    | '/dashboard/guud-friends'
    | '/dashboard/my-dashboard'
    | '/dashboard/nfts'
    | '/dashboard/referral-stats'
    | '/dashboard/score'
    | '/dashboard/vouch'
    | '/profile/$username'
    | '/profile/settings'
    | '/shop/customization'
    | '/shop/mint'
    | '/shop/order-status'
    | '/shop/payout'
    | '/dashboard/'
    | '/profile/'
    | '/shop/'
    | '/auth/callback/twitter'
    | '/profile/settings/appearance'
    | '/profile/settings/arena'
    | '/profile/settings/basic'
    | '/profile/settings/bribe'
    | '/profile/settings/nfts'
    | '/profile/settings/social'
    | '/profile/settings/style'
    | '/profile/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/leaderboard'
    | '/login'
    | '/ref'
    | '/register'
    | '/agent-profile/$agentId'
    | '/auth/error'
    | '/dashboard/arena-yapping'
    | '/dashboard/assets'
    | '/dashboard/bribe'
    | '/dashboard/guud-card'
    | '/dashboard/guud-friends'
    | '/dashboard/my-dashboard'
    | '/dashboard/nfts'
    | '/dashboard/referral-stats'
    | '/dashboard/score'
    | '/dashboard/vouch'
    | '/profile/$username'
    | '/shop/customization'
    | '/shop/mint'
    | '/shop/order-status'
    | '/shop/payout'
    | '/dashboard'
    | '/profile'
    | '/shop'
    | '/auth/callback/twitter'
    | '/profile/settings/appearance'
    | '/profile/settings/arena'
    | '/profile/settings/basic'
    | '/profile/settings/bribe'
    | '/profile/settings/nfts'
    | '/profile/settings/social'
    | '/profile/settings/style'
    | '/profile/settings'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/leaderboard'
    | '/login'
    | '/profile'
    | '/ref'
    | '/register'
    | '/shop'
    | '/agent-profile/$agentId'
    | '/auth/error'
    | '/dashboard/arena-yapping'
    | '/dashboard/assets'
    | '/dashboard/bribe'
    | '/dashboard/guud-card'
    | '/dashboard/guud-friends'
    | '/dashboard/my-dashboard'
    | '/dashboard/nfts'
    | '/dashboard/referral-stats'
    | '/dashboard/score'
    | '/dashboard/vouch'
    | '/profile/$username'
    | '/profile/settings'
    | '/shop/customization'
    | '/shop/mint'
    | '/shop/order-status'
    | '/shop/payout'
    | '/dashboard/'
    | '/profile/'
    | '/shop/'
    | '/auth/callback/twitter'
    | '/profile/settings/appearance'
    | '/profile/settings/arena'
    | '/profile/settings/basic'
    | '/profile/settings/bribe'
    | '/profile/settings/nfts'
    | '/profile/settings/social'
    | '/profile/settings/style'
    | '/profile/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LeaderboardRoute: typeof LeaderboardRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRouteWithChildren
  RefRoute: typeof RefRoute
  RegisterRoute: typeof RegisterRoute
  ShopRoute: typeof ShopRouteWithChildren
  AgentProfileAgentIdRoute: typeof AgentProfileAgentIdRoute
  AuthErrorRoute: typeof AuthErrorRoute
  AuthCallbackTwitterRoute: typeof AuthCallbackTwitterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ref': {
      id: '/ref'
      path: '/ref'
      fullPath: '/ref'
      preLoaderRoute: typeof RefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/': {
      id: '/shop/'
      path: '/'
      fullPath: '/shop/'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof ShopRoute
    }
    '/profile/': {
      id: '/profile/'
      path: '/'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/shop/payout': {
      id: '/shop/payout'
      path: '/payout'
      fullPath: '/shop/payout'
      preLoaderRoute: typeof ShopPayoutRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/order-status': {
      id: '/shop/order-status'
      path: '/order-status'
      fullPath: '/shop/order-status'
      preLoaderRoute: typeof ShopOrderStatusRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/mint': {
      id: '/shop/mint'
      path: '/mint'
      fullPath: '/shop/mint'
      preLoaderRoute: typeof ShopMintRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/customization': {
      id: '/shop/customization'
      path: '/customization'
      fullPath: '/shop/customization'
      preLoaderRoute: typeof ShopCustomizationRouteImport
      parentRoute: typeof ShopRoute
    }
    '/profile/settings': {
      id: '/profile/settings'
      path: '/settings'
      fullPath: '/profile/settings'
      preLoaderRoute: typeof ProfileSettingsRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/profile/$username': {
      id: '/profile/$username'
      path: '/$username'
      fullPath: '/profile/$username'
      preLoaderRoute: typeof ProfileUsernameRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/dashboard/vouch': {
      id: '/dashboard/vouch'
      path: '/vouch'
      fullPath: '/dashboard/vouch'
      preLoaderRoute: typeof DashboardVouchRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/score': {
      id: '/dashboard/score'
      path: '/score'
      fullPath: '/dashboard/score'
      preLoaderRoute: typeof DashboardScoreRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/referral-stats': {
      id: '/dashboard/referral-stats'
      path: '/referral-stats'
      fullPath: '/dashboard/referral-stats'
      preLoaderRoute: typeof DashboardReferralStatsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/nfts': {
      id: '/dashboard/nfts'
      path: '/nfts'
      fullPath: '/dashboard/nfts'
      preLoaderRoute: typeof DashboardNftsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/my-dashboard': {
      id: '/dashboard/my-dashboard'
      path: '/my-dashboard'
      fullPath: '/dashboard/my-dashboard'
      preLoaderRoute: typeof DashboardMyDashboardRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/guud-friends': {
      id: '/dashboard/guud-friends'
      path: '/guud-friends'
      fullPath: '/dashboard/guud-friends'
      preLoaderRoute: typeof DashboardGuudFriendsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/guud-card': {
      id: '/dashboard/guud-card'
      path: '/guud-card'
      fullPath: '/dashboard/guud-card'
      preLoaderRoute: typeof DashboardGuudCardRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/bribe': {
      id: '/dashboard/bribe'
      path: '/bribe'
      fullPath: '/dashboard/bribe'
      preLoaderRoute: typeof DashboardBribeRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/assets': {
      id: '/dashboard/assets'
      path: '/assets'
      fullPath: '/dashboard/assets'
      preLoaderRoute: typeof DashboardAssetsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/arena-yapping': {
      id: '/dashboard/arena-yapping'
      path: '/arena-yapping'
      fullPath: '/dashboard/arena-yapping'
      preLoaderRoute: typeof DashboardArenaYappingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/auth/error': {
      id: '/auth/error'
      path: '/auth/error'
      fullPath: '/auth/error'
      preLoaderRoute: typeof AuthErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent-profile/$agentId': {
      id: '/agent-profile/$agentId'
      path: '/agent-profile/$agentId'
      fullPath: '/agent-profile/$agentId'
      preLoaderRoute: typeof AgentProfileAgentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/settings/': {
      id: '/profile/settings/'
      path: '/'
      fullPath: '/profile/settings/'
      preLoaderRoute: typeof ProfileSettingsIndexRouteImport
      parentRoute: typeof ProfileSettingsRoute
    }
    '/profile/settings/style': {
      id: '/profile/settings/style'
      path: '/style'
      fullPath: '/profile/settings/style'
      preLoaderRoute: typeof ProfileSettingsStyleRouteImport
      parentRoute: typeof ProfileSettingsRoute
    }
    '/profile/settings/social': {
      id: '/profile/settings/social'
      path: '/social'
      fullPath: '/profile/settings/social'
      preLoaderRoute: typeof ProfileSettingsSocialRouteImport
      parentRoute: typeof ProfileSettingsRoute
    }
    '/profile/settings/nfts': {
      id: '/profile/settings/nfts'
      path: '/nfts'
      fullPath: '/profile/settings/nfts'
      preLoaderRoute: typeof ProfileSettingsNftsRouteImport
      parentRoute: typeof ProfileSettingsRoute
    }
    '/profile/settings/bribe': {
      id: '/profile/settings/bribe'
      path: '/bribe'
      fullPath: '/profile/settings/bribe'
      preLoaderRoute: typeof ProfileSettingsBribeRouteImport
      parentRoute: typeof ProfileSettingsRoute
    }
    '/profile/settings/basic': {
      id: '/profile/settings/basic'
      path: '/basic'
      fullPath: '/profile/settings/basic'
      preLoaderRoute: typeof ProfileSettingsBasicRouteImport
      parentRoute: typeof ProfileSettingsRoute
    }
    '/profile/settings/arena': {
      id: '/profile/settings/arena'
      path: '/arena'
      fullPath: '/profile/settings/arena'
      preLoaderRoute: typeof ProfileSettingsArenaRouteImport
      parentRoute: typeof ProfileSettingsRoute
    }
    '/profile/settings/appearance': {
      id: '/profile/settings/appearance'
      path: '/appearance'
      fullPath: '/profile/settings/appearance'
      preLoaderRoute: typeof ProfileSettingsAppearanceRouteImport
      parentRoute: typeof ProfileSettingsRoute
    }
    '/auth/callback/twitter': {
      id: '/auth/callback/twitter'
      path: '/auth/callback/twitter'
      fullPath: '/auth/callback/twitter'
      preLoaderRoute: typeof AuthCallbackTwitterRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardArenaYappingRoute: typeof DashboardArenaYappingRoute
  DashboardAssetsRoute: typeof DashboardAssetsRoute
  DashboardBribeRoute: typeof DashboardBribeRoute
  DashboardGuudCardRoute: typeof DashboardGuudCardRoute
  DashboardGuudFriendsRoute: typeof DashboardGuudFriendsRoute
  DashboardMyDashboardRoute: typeof DashboardMyDashboardRoute
  DashboardNftsRoute: typeof DashboardNftsRoute
  DashboardReferralStatsRoute: typeof DashboardReferralStatsRoute
  DashboardScoreRoute: typeof DashboardScoreRoute
  DashboardVouchRoute: typeof DashboardVouchRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardArenaYappingRoute: DashboardArenaYappingRoute,
  DashboardAssetsRoute: DashboardAssetsRoute,
  DashboardBribeRoute: DashboardBribeRoute,
  DashboardGuudCardRoute: DashboardGuudCardRoute,
  DashboardGuudFriendsRoute: DashboardGuudFriendsRoute,
  DashboardMyDashboardRoute: DashboardMyDashboardRoute,
  DashboardNftsRoute: DashboardNftsRoute,
  DashboardReferralStatsRoute: DashboardReferralStatsRoute,
  DashboardScoreRoute: DashboardScoreRoute,
  DashboardVouchRoute: DashboardVouchRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface ProfileSettingsRouteChildren {
  ProfileSettingsAppearanceRoute: typeof ProfileSettingsAppearanceRoute
  ProfileSettingsArenaRoute: typeof ProfileSettingsArenaRoute
  ProfileSettingsBasicRoute: typeof ProfileSettingsBasicRoute
  ProfileSettingsBribeRoute: typeof ProfileSettingsBribeRoute
  ProfileSettingsNftsRoute: typeof ProfileSettingsNftsRoute
  ProfileSettingsSocialRoute: typeof ProfileSettingsSocialRoute
  ProfileSettingsStyleRoute: typeof ProfileSettingsStyleRoute
  ProfileSettingsIndexRoute: typeof ProfileSettingsIndexRoute
}

const ProfileSettingsRouteChildren: ProfileSettingsRouteChildren = {
  ProfileSettingsAppearanceRoute: ProfileSettingsAppearanceRoute,
  ProfileSettingsArenaRoute: ProfileSettingsArenaRoute,
  ProfileSettingsBasicRoute: ProfileSettingsBasicRoute,
  ProfileSettingsBribeRoute: ProfileSettingsBribeRoute,
  ProfileSettingsNftsRoute: ProfileSettingsNftsRoute,
  ProfileSettingsSocialRoute: ProfileSettingsSocialRoute,
  ProfileSettingsStyleRoute: ProfileSettingsStyleRoute,
  ProfileSettingsIndexRoute: ProfileSettingsIndexRoute,
}

const ProfileSettingsRouteWithChildren = ProfileSettingsRoute._addFileChildren(
  ProfileSettingsRouteChildren,
)

interface ProfileRouteChildren {
  ProfileUsernameRoute: typeof ProfileUsernameRoute
  ProfileSettingsRoute: typeof ProfileSettingsRouteWithChildren
  ProfileIndexRoute: typeof ProfileIndexRoute
}

const ProfileRouteChildren: ProfileRouteChildren = {
  ProfileUsernameRoute: ProfileUsernameRoute,
  ProfileSettingsRoute: ProfileSettingsRouteWithChildren,
  ProfileIndexRoute: ProfileIndexRoute,
}

const ProfileRouteWithChildren =
  ProfileRoute._addFileChildren(ProfileRouteChildren)

interface ShopRouteChildren {
  ShopCustomizationRoute: typeof ShopCustomizationRoute
  ShopMintRoute: typeof ShopMintRoute
  ShopOrderStatusRoute: typeof ShopOrderStatusRoute
  ShopPayoutRoute: typeof ShopPayoutRoute
  ShopIndexRoute: typeof ShopIndexRoute
}

const ShopRouteChildren: ShopRouteChildren = {
  ShopCustomizationRoute: ShopCustomizationRoute,
  ShopMintRoute: ShopMintRoute,
  ShopOrderStatusRoute: ShopOrderStatusRoute,
  ShopPayoutRoute: ShopPayoutRoute,
  ShopIndexRoute: ShopIndexRoute,
}

const ShopRouteWithChildren = ShopRoute._addFileChildren(ShopRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LeaderboardRoute: LeaderboardRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRouteWithChildren,
  RefRoute: RefRoute,
  RegisterRoute: RegisterRoute,
  ShopRoute: ShopRouteWithChildren,
  AgentProfileAgentIdRoute: AgentProfileAgentIdRoute,
  AuthErrorRoute: AuthErrorRoute,
  AuthCallbackTwitterRoute: AuthCallbackTwitterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
